name: $(date:yyyyMMdd)$(rev:.r)

pr:
   autoCancel: true
   branches:
     include:
       - master

pool:
  name: iDokladBuild
workspace:
  clean: resources

variables:
  buildConfiguration: 'Release'

steps:
- task: FileTransform@2
  displayName: 'Substitute settings'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    jsonTargetFiles: 'IdokladSdk.IntegrationTests/testsettings.json'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Run Unit tests"
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --logger trx'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Run Integration tests'
  inputs:
    command: 'test'
    projects: '**/*IntegrationTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --logger trx'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: "Create NuGet package"
  inputs:
    command: 'pack'
    packagesToPack: '**/IdokladSdk.csproj'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: NuGetCommand@2
  displayName: "Publish NuGet package"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/IdokladSdk*.nupkg;!$(Build.ArtifactStagingDirectory)/**/IdokladSdk*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4648ca4e-87a8-47c4-ab02-16dcea8269c2/ff881867-c73f-4290-beaa-f96019a33788'
    allowPackageConflicts: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  
- task: DeleteFiles@1
  displayName: 'Delete files'
  inputs:
    Contents: '**/*'
  continueOnError: true
  condition: always()

